/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CuartaActividad;

import javax.swing.JTextArea;

/**
 *
 * @author jesus agudelo
 */
public class AyudaPlantilla extends javax.swing.JFrame {

    /**
     * Creates new form AyudaPlantilla
     */
    public AyudaPlantilla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        LogoHome2 = new javax.swing.JButton();
        AyudaT = new javax.swing.JLabel();
        Rectangulo14 = new javax.swing.JLabel();
        Rectangulo13 = new javax.swing.JLabel();
        Rectangulo12 = new javax.swing.JLabel();
        Rectangulo11 = new javax.swing.JLabel();
        Fondo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setBackground(new java.awt.Color(55, 107, 46));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Inicio de sesión\nPara iniciar sesión en nuestra plataforma, sigue estos pasos:\n1.Ingresa tu dirección de email en el campo “Email”.\n2.Ingresa tu contraseña en el campo “Contraseña”.\n3.Haz clic en el botón “Iniciar sesión”.\nSi has olvidado tu contraseña, haz clic en el enlace “¿Olvidaste tu contraseña? ”\n y sigue las instrucciones para restablecerla.\n\nRegistro\nSi eres nuevo en nuestra plataforma y deseas registrarte, sigue estos pasos:\nHaz clic en el enlace “Crear nueva cuenta”.\nCompleta el formulario de registro con tu nombre, apellidos, correo electrónico y contraseña.\nHaz clic en el botón “Registrarse” para completar tu registro.\nUna vez que te hayas registrado, podrás iniciar sesión con tu nombre de usuario y contraseña.\n\nAcerca del creador de la plantilla\nEsta plantilla fue creada por Jesus Esteban Agudelo Orozco, estudiante de Ingeniería de \nSistemas de la Universidad del Sinú seccional Cartagena. ");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 430, 260));

        LogoHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/adobe-photoshop.png"))); // NOI18N
        LogoHome2.setContentAreaFilled(false);
        getContentPane().add(LogoHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        AyudaT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        AyudaT.setText("Ayuda");
        getContentPane().add(AyudaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 70, 30));

        Rectangulo14.setBackground(new java.awt.Color(55, 107, 46));
        Rectangulo14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Rectangulo14.setOpaque(true);
        getContentPane().add(Rectangulo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 470, 400));

        Rectangulo13.setBackground(new java.awt.Color(111, 78, 55));
        Rectangulo13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Rectangulo13.setOpaque(true);
        getContentPane().add(Rectangulo13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 470, 400));

        Rectangulo12.setBackground(new java.awt.Color(255, 215, 0));
        Rectangulo12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Rectangulo12.setOpaque(true);
        getContentPane().add(Rectangulo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 470, 400));

        Rectangulo11.setBackground(new java.awt.Color(255, 0, 255));
        Rectangulo11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Rectangulo11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Rectangulo11.setOpaque(true);
        getContentPane().add(Rectangulo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 470, 400));

        Fondo4.setBackground(new java.awt.Color(153, 153, 153));
        Fondo4.setOpaque(true);
        getContentPane().add(Fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AyudaPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AyudaPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AyudaPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AyudaPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AyudaPlantilla().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AyudaT;
    private javax.swing.JLabel Fondo4;
    private javax.swing.JButton LogoHome2;
    private javax.swing.JLabel Rectangulo11;
    private javax.swing.JLabel Rectangulo12;
    private javax.swing.JLabel Rectangulo13;
    private javax.swing.JLabel Rectangulo14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
