/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CuartaActividad;

/**
 *
 * @author jesus agudelo
 */
public class RecoverPlantilla extends javax.swing.JFrame {

    /**
     * Creates new form RecoverPlantilla
     */
    public RecoverPlantilla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        Codigo = new javax.swing.JLabel();
        Tett = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Mail3 = new javax.swing.JLabel();
        Cont = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Ayuda2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Email2 = new javax.swing.JTextField();
        Mail2 = new javax.swing.JLabel();
        LogoHome1 = new javax.swing.JButton();
        RecoveryT = new javax.swing.JLabel();
        Rectangulo9 = new javax.swing.JLabel();
        Rectangulo8 = new javax.swing.JLabel();
        Rectangulo7 = new javax.swing.JLabel();
        Rectangulo10 = new javax.swing.JLabel();
        Fondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/numerico.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        Codigo.setText("Codigo");
        getContentPane().add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 40, 30));

        Tett.setBackground(new java.awt.Color(204, 204, 204));
        Tett.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TettActionPerformed(evt);
            }
        });
        getContentPane().add(Tett, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 160, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bloquear (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        Mail3.setText("Contraseña Nueva");
        getContentPane().add(Mail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 120, 30));

        Cont.setBackground(new java.awt.Color(204, 204, 204));
        Cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContActionPerformed(evt);
            }
        });
        getContentPane().add(Cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 210, 30));

        jButton3.setBackground(new java.awt.Color(55, 107, 46));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("Enviar codigo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/email (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        Ayuda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informacion.png"))); // NOI18N
        Ayuda2.setContentAreaFilled(false);
        Ayuda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ayuda2ActionPerformed(evt);
            }
        });
        getContentPane().add(Ayuda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        jButton1.setBackground(new java.awt.Color(55, 107, 46));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Recuperar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        Email2.setBackground(new java.awt.Color(204, 204, 204));
        Email2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email2ActionPerformed(evt);
            }
        });
        getContentPane().add(Email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 160, 30));

        Mail2.setText("Email");
        getContentPane().add(Mail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 40, 30));

        LogoHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/adobe-photoshop.png"))); // NOI18N
        LogoHome1.setContentAreaFilled(false);
        getContentPane().add(LogoHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        RecoveryT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        RecoveryT.setText("Recover password");
        getContentPane().add(RecoveryT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 170, 30));

        Rectangulo9.setBackground(new java.awt.Color(111, 78, 55));
        Rectangulo9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Rectangulo9.setOpaque(true);
        getContentPane().add(Rectangulo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 370, 290));

        Rectangulo8.setBackground(new java.awt.Color(55, 107, 46));
        Rectangulo8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Rectangulo8.setOpaque(true);
        getContentPane().add(Rectangulo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 370, 290));

        Rectangulo7.setBackground(new java.awt.Color(255, 215, 0));
        Rectangulo7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Rectangulo7.setOpaque(true);
        getContentPane().add(Rectangulo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 370, 290));

        Rectangulo10.setBackground(new java.awt.Color(255, 0, 255));
        Rectangulo10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Rectangulo10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Rectangulo10.setOpaque(true);
        getContentPane().add(Rectangulo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 370, 290));

        Fondo3.setBackground(new java.awt.Color(153, 153, 153));
        Fondo3.setOpaque(true);
        getContentPane().add(Fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ayuda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ayuda2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ayuda2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Email2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContActionPerformed

    private void TettActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TettActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TettActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecoverPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecoverPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecoverPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecoverPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoverPlantilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ayuda2;
    private javax.swing.JLabel Codigo;
    private javax.swing.JTextField Cont;
    private javax.swing.JTextField Email2;
    private javax.swing.JLabel Fondo3;
    private javax.swing.JButton LogoHome1;
    private javax.swing.JLabel Mail2;
    private javax.swing.JLabel Mail3;
    private javax.swing.JLabel RecoveryT;
    private javax.swing.JLabel Rectangulo10;
    private javax.swing.JLabel Rectangulo7;
    private javax.swing.JLabel Rectangulo8;
    private javax.swing.JLabel Rectangulo9;
    private javax.swing.JTextField Tett;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
