/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CuartaActividad;

/**
 *
 * @author jesus agudelo
 */
public class RegisterPlantilla extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPlantilla
     */
    public RegisterPlantilla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoHome = new javax.swing.JButton();
        Ayuda1 = new javax.swing.JButton();
        Mail1 = new javax.swing.JLabel();
        Mail = new javax.swing.JLabel();
        Passw1 = new javax.swing.JLabel();
        Passw = new javax.swing.JLabel();
        LastN = new javax.swing.JLabel();
        Names = new javax.swing.JLabel();
        CrearC = new javax.swing.JButton();
        Email1 = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        RegisterTexto = new javax.swing.JLabel();
        UserLastNDatos = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        UserNameDatos2 = new javax.swing.JTextField();
        Rectangulo6 = new javax.swing.JLabel();
        Rectangulo5 = new javax.swing.JLabel();
        Rectangulo4 = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/adobe-photoshop.png"))); // NOI18N
        LogoHome.setContentAreaFilled(false);
        getContentPane().add(LogoHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        Ayuda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informacion.png"))); // NOI18N
        Ayuda1.setContentAreaFilled(false);
        Ayuda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ayuda1ActionPerformed(evt);
            }
        });
        getContentPane().add(Ayuda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, -1));

        Mail1.setText("Confirmar Email");
        getContentPane().add(Mail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 90, 30));

        Mail.setText("Email");
        getContentPane().add(Mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 40, 30));

        Passw1.setText("Confirmar Contraseña");
        getContentPane().add(Passw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 130, 30));

        Passw.setText("Contraseña");
        getContentPane().add(Passw, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 80, 30));

        LastN.setText("Apellidos");
        getContentPane().add(LastN, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 60, 30));

        Names.setText("Nombre");
        getContentPane().add(Names, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 60, 30));

        CrearC.setBackground(new java.awt.Color(55, 107, 46));
        CrearC.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CrearC.setText("Crear Cuenta ");
        CrearC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCActionPerformed(evt);
            }
        });
        getContentPane().add(CrearC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        Email1.setBackground(new java.awt.Color(204, 204, 204));
        Email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email1ActionPerformed(evt);
            }
        });
        getContentPane().add(Email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 130, 30));

        Email.setBackground(new java.awt.Color(204, 204, 204));
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 130, 30));

        RegisterTexto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        RegisterTexto.setText("REGISTER");
        getContentPane().add(RegisterTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 90, 30));

        UserLastNDatos.setBackground(new java.awt.Color(204, 204, 204));
        UserLastNDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLastNDatosActionPerformed(evt);
            }
        });
        getContentPane().add(UserLastNDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 130, 30));

        jPasswordField2.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 130, 30));

        jPasswordField3.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 130, 30));

        UserNameDatos2.setBackground(new java.awt.Color(204, 204, 204));
        UserNameDatos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameDatos2ActionPerformed(evt);
            }
        });
        getContentPane().add(UserNameDatos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 130, 30));

        Rectangulo6.setBackground(new java.awt.Color(255, 215, 0));
        Rectangulo6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Rectangulo6.setOpaque(true);
        getContentPane().add(Rectangulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 370, 290));

        Rectangulo5.setBackground(new java.awt.Color(191, 163, 10));
        Rectangulo5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Rectangulo5.setOpaque(true);
        getContentPane().add(Rectangulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 370, 290));

        Rectangulo4.setBackground(new java.awt.Color(125, 106, 4));
        Rectangulo4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Rectangulo4.setOpaque(true);
        getContentPane().add(Rectangulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 370, 280));

        Fondo2.setBackground(new java.awt.Color(55, 107, 46));
        Fondo2.setOpaque(true);
        getContentPane().add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ayuda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ayuda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ayuda1ActionPerformed

    private void CrearCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearCActionPerformed

    private void Email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email1ActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void UserLastNDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLastNDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserLastNDatosActionPerformed

    private void UserNameDatos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameDatos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameDatos2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPlantilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ayuda1;
    private javax.swing.JButton CrearC;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Email1;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JLabel LastN;
    private javax.swing.JButton LogoHome;
    private javax.swing.JLabel Mail;
    private javax.swing.JLabel Mail1;
    private javax.swing.JLabel Names;
    private javax.swing.JLabel Passw;
    private javax.swing.JLabel Passw1;
    private javax.swing.JLabel Rectangulo4;
    private javax.swing.JLabel Rectangulo5;
    private javax.swing.JLabel Rectangulo6;
    private javax.swing.JLabel RegisterTexto;
    private javax.swing.JTextField UserLastNDatos;
    private javax.swing.JTextField UserNameDatos2;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    // End of variables declaration//GEN-END:variables
}
