/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CuartaActividad;

/**
 *
 * @author jesus agudelo
 */
public class VentanaAcceso extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAcceso
     */
    public VentanaAcceso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IniciarS = new javax.swing.JButton();
        CrearCuenta = new javax.swing.JButton();
        Olvidar = new javax.swing.JButton();
        Ayuda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        LoginTexto = new javax.swing.JLabel();
        Recuerdame = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        UserNameDatos = new javax.swing.JTextField();
        Rectangulo3 = new javax.swing.JLabel();
        Rectangulo2 = new javax.swing.JLabel();
        Rectangulo1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bloquear (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/email (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        IniciarS.setBackground(new java.awt.Color(255, 215, 0));
        IniciarS.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        IniciarS.setText("Iniciar Sesión");
        IniciarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSActionPerformed(evt);
            }
        });
        getContentPane().add(IniciarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        CrearCuenta.setText("Crear nueva cuenta");
        CrearCuenta.setContentAreaFilled(false);
        CrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(CrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        Olvidar.setText("¿Olvidaste tu contraseña?");
        Olvidar.setContentAreaFilled(false);
        getContentPane().add(Olvidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 180, -1));

        Ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informacion.png"))); // NOI18N
        Ayuda.setContentAreaFilled(false);
        Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaActionPerformed(evt);
            }
        });
        getContentPane().add(Ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/adobe-photoshop.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 20, 20));

        LoginTexto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LoginTexto.setText("LOGIN");
        getContentPane().add(LoginTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 60, 30));

        Recuerdame.setText("Recuérdame");
        getContentPane().add(Recuerdame, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 80, 20));

        jLabel1.setText("Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 60, 30));

        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 60, 30));

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 210, 30));

        UserNameDatos.setBackground(new java.awt.Color(204, 204, 204));
        UserNameDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameDatosActionPerformed(evt);
            }
        });
        getContentPane().add(UserNameDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 210, 30));

        Rectangulo3.setBackground(new java.awt.Color(55, 107, 46));
        Rectangulo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Rectangulo3.setOpaque(true);
        getContentPane().add(Rectangulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 370, 280));

        Rectangulo2.setBackground(new java.awt.Color(49, 87, 42));
        Rectangulo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Rectangulo2.setOpaque(true);
        getContentPane().add(Rectangulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 370, 280));

        Rectangulo1.setBackground(new java.awt.Color(24, 43, 20));
        Rectangulo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Rectangulo1.setOpaque(true);
        getContentPane().add(Rectangulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 370, 280));

        Fondo.setBackground(new java.awt.Color(255, 215, 0));
        Fondo.setOpaque(true);
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameDatosActionPerformed

    private void AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AyudaActionPerformed

    private void CrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearCuentaActionPerformed

    private void IniciarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IniciarSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAcceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ayuda;
    private javax.swing.JButton CrearCuenta;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton IniciarS;
    private javax.swing.JLabel LoginTexto;
    private javax.swing.JButton Olvidar;
    private javax.swing.JLabel Rectangulo1;
    private javax.swing.JLabel Rectangulo2;
    private javax.swing.JLabel Rectangulo3;
    private javax.swing.JLabel Recuerdame;
    private javax.swing.JTextField UserNameDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
